### PR TITLE
Adding status code field to Response class (interface)

### PR DESCRIPTION
**Pull request by busslina**
Adding missing status code field to Response class interface

### CODE REVIEW

**Comment by paulober** [comment]
Which firmware have you used? 
I have not found the status_code field implemented in the current pico w mpy firmware...

Also please open PRs concerning the stubs in the github.com/paulober/Pico-W-Stub for future changes

**Comment by busslina** [comment]
@paulober I have used rp2-pico-w-20230207-unstable-v1.19.1-854-g35524a6fd.

Okay, I will try to open PR on stub repo

**Comment by busslina** [comment]
PR https://github.com/paulober/Pico-W-Stub/pull/3

**Comment by paulober** [comment]
See https://github.com/paulober/Pico-W-Stub/pull/3 and paulober/Pico-W-Stub@9b6051c

**Pull request closed without merging**
